language: objective-c
matrix:
  include:
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode9.3beta
branches:
  only:
    - master
script:
  make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
